src/main/java/cz/tomrechtig/domain/entities/Order.java
package cz.tomrechtig.domain.entities;

import cz.tomrechtig.domain.entities.definition.IBook;
import cz.tomrechtig.domain.entities.definition.IOrder;
import cz.tomrechtig.domain.entities.definition.IUser;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Order implements IOrder, Serializable {

    private Long id;

    private IUser user;

    private List<IBook> books;

    private Date createdDate;

    private Date updatedDate;

    public Order(Long id, IUser user, List<IBook> books, Date createdDate, Date updatedDate) {
        this.id = id;
        this.user = user;
        this.books = books;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public IUser getUser() {
        return user;
    }

    @Override
    public void setUser(IUser user) {
        this.user = user;
    }

    @Override
    public Long getUserId() {
        return id;
    }

    @Override
    public List<IBook> getBooks() {
        return books;
    }

    @Override
    public void setBooks(List<IBook> books) {
        this.books = books;
    }

    @Override
    public Date getCreatedDate() {
        return createdDate;
    }

    @Override
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Override
    public Date getUpdatedDate() {
        return updatedDate;
    }

    @Override
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}

src/main/java/cz/tomrechtig/presentation/entities/CurrentUser.java
package cz.tomrechtig.presentation.entities;

import cz.tomrechtig.domain.entities.definition.IBook;
import cz.tomrechtig.domain.entities.definition.IUser;
import cz.tomrechtig.presentation.entities.definition.ICurrentUser;

import java.util.ArrayList;
import java.util.List;

public class CurrentUser implements ICurrentUser {

    private Long id;

    private String username;

    private String email;

    private String password;

    private final List<IBook> cart;

    public CurrentUser(Long id, String username, String email, String password, List<IBook> cart) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.password = password;
        this.cart = cart;
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String getUsername() {
        return username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String getEmail() {
        return email;
    }

    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String getPassword() {
        return password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public List<IBook> getCart() {
        return cart;
    }

    @Override
    public int getCartSize() {
        return cart.size();
    }

    @Override
    public void addToCart(IBook book) {
        cart.add(book);
    }

    @Override
    public void removeFromCart(IBook book) {
        cart.remove(book);
    }
}

src/main/webapp/pages/cart.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <ui:composition template="../templates/common/layout.xhtml">
        <ui:define name="title">SHOPIK | My Cart</ui:define>
        <ui:define name="content">
            <div class="container mt-5">
                <div class="row">
                    <h:form styleClass="col-12">
                        <h:commandButton action="home" styleClass="btn btn-secondary btn-sm" value="Back" />
                    </h:form>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2 class="my-3">My Cart</h2>
                    </div>
                </div>
                <div class="row">
                    <h:form styleClass="col-12" rendered="#{userController.currentUser.cartSize > 0}">
                        <ul class="list-group">
                            <ui:repeat value="#{userController.currentUser.cart}" var="book">
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    #{book.title}
                                    <h:commandButton styleClass="btn btn-danger btn-sm" action="#{userController.removeFromCart(book)}" value="Remove"/>
                                </li>
                            </ui:repeat>
                        </ul>
                    </h:form>
                    <h:panelGrid rendered="#{userController.currentUser.cartSize == 0}">
                        <p class="text-center col-12">There is nothing in your cart</p>
                    </h:panelGrid>
                </div>

                <div class="row mt-5">
                    <h:form class="col-12 d-flex justify-content-end">
                        <h:commandButton styleClass="btn btn-success btn-sm" action="#{userController.createOrder()}" value="Buy"/>
                    </h:form>
                </div>
            </div>

        </ui:define>
    </ui:composition>
</f:view>
</html>

src/main/webapp/pages/orders.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <ui:composition template="../templates/common/layout.xhtml">
        <ui:define name="title">SHOPIK | My Orders</ui:define>
        <ui:define name="content">
            <div class="container mt-5">
                <div class="row">
                    <h:form styleClass="col-12">
                        <h:commandButton action="home" styleClass="btn btn-secondary btn-sm" value="Back" />
                    </h:form>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2 class="my-3">My Orders</h2>
                    </div>
                </div>
                <div class="row">
                    <h:form styleClass="col-12" rendered="#{userController.ordersSize > 0}">
                        <ul class="list-group">
                            <ui:repeat value="#{userController.orders}" var="order">
                                <li class="list-group-item d-flex flex-column p-5">
                                    <p class="lead">Order ##{order.id}</p>
                                    <p class="small mb-0 text-muted" style="margin-left: 1.25rem">ordered books:</p>

                                    <ul class="list-group list-group-flush">
                                        <ui:repeat value="#{order.books}" var="book">
                                            <li class="list-group-item d-flex align-items-center">
                                                <p class="mb-0"><span style="font-weight: bold;">#{book.title}</span> <span class="small">by #{book.author}</span></p>
                                            </li>
                                        </ui:repeat>
                                    </ul>

                                </li>
                            </ui:repeat>
                        </ul>
                    </h:form>
                    <h:panelGrid rendered="#{userController.ordersSize == 0}">
                        <p class="text-center col-12">There are no orders, yet!</p>
                    </h:panelGrid>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</f:view>
</html>